/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nizkjnidemo_NizkJniKit */

#ifndef _Included_com_nizkjnidemo_NizkJniKit
#define _Included_com_nizkjnidemo_NizkJniKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nizkjnidemo_NizkJniKit
 * Method:    getPubKey
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nizkjnidemo_NizkJniKit_getPubKey
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_nizkjnidemo_NizkJniKit
 * Method:    NIZK_Encryption
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nizkjnidemo_NizkJniKit_NIZK_1Encryption
  (JNIEnv *, jclass, jstring, jint, jstring, jint);

/*
 * Class:     com_nizkjnidemo_NizkJniKit
 * Method:    NIZK_Decryption
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nizkjnidemo_NizkJniKit_NIZK_1Decryption
  (JNIEnv *, jclass, jstring, jint, jstring, jint, jstring, jint);

/*
 * Class:     com_nizkjnidemo_NizkJniKit
 * Method:    NIZK_GenProof
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nizkjnidemo_NizkJniKit_NIZK_1GenProof
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jstring, jint, jstring, jint, jstring, jint, jstring, jint);

/*
 * Class:     com_nizkjnidemo_NizkJniKit
 * Method:    NIZK_VerifyProof
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nizkjnidemo_NizkJniKit_NIZK_1VerifyProof
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
